const chatWrapper=document.getElementById('chatWrapper');const loader=document.getElementById('loader');const topicList=document.getElementById('topicList');const senderList=document.getElementById('senderList');const chatOutput=document.getElementById('chatOutput');const goUpBtn=document.getElementById('goUp');const goDownBtn=document.getElementById('goDown');const headingArea=document.getElementById('headingArea');const tabsArea=document.getElementById('tabsArea');const navButtons=document.getElementById('navButtons');const printbtn=document.getElementsByClassName('fullyloaded');const timer=document.getElementById('timer')
var modal=document.getElementById("myModal");var span=document.getElementsByClassName("close")[0];span.onclick=function(){modal.style.display="none"}
window.onclick=function(event){if(event.target==modal){modal.style.display="none"}}
let allMessages=[];all1.shift()
all0=[...all0,...all1]
allMessages=parseRawMessages(all0);showTopics();showSenders();window.onload=async function(){try{const response=await fetch('https://script.google.com/macros/s/AKfycbzGpguV0hLcJzvU2PLC70zaSJqiw-MPxtD_QKlKsuDV-s7UYb0EPMIYf_gTeoRCeA2cXg/exec');data=await response.json();filterupto=data[0][9]
maxsl=data[0][12]
data=[...all0,...data]
data=parseRawMessages(data);allMessages=data
almsl=allMessages.length+3
msgdif=maxsl-almsl
msgdif===0?modal.style.display='none':modal.style.display='block'
timer.style.display="none";showTopics();showSenders();printbtn[0].style.color='red'
printbtn[1].style.color='yellow'}catch(e){topicList.innerHTML='<p style="color:red;">Error loading chat data.</p>'}finally{}};function parseRawMessages(data){const regex=/^\[(\d{2})\/(\d{2})\/(\d{4}),(\d{2}):(\d{2}):(\d{2})\]~?\s?\u202f?(.*?):(.*)/s;let parsed=[];let current=null;data.forEach(row=>{if(!Array.isArray(row)||typeof row[0]!=='string')return;const line=row[0];const topics=typeof row[7]==='string'?row[7].split(',').map(t=>t.trim()):[];const subtopic=row[7]||'';const serial=parseInt(row[4]);const chainTo=parseInt(row[5]);const match=line.match(regex);if(match){if(current)parsed.push(current);const[_,day,month,year,hour,minute,second,sender,message]=match;const date=`${day}/${month}/${year}`;const isoDate=`${year}-${month}-${day}`;const time=`${hour}:${minute}:${second}`;current={date,isoDate,time,sender,message,topics,subtopic,serial,chainTo,chainExtract:''}}else if(current){current.message+='\n'+line}});if(current)parsed.push(current);const serialMap=new Map(parsed.map(m=>[m.serial,m]));parsed.forEach(m=>{if(m.chainTo&&serialMap.has(m.chainTo)){const ref=serialMap.get(m.chainTo);if(ref){const shortMsg=ref.message.length>100?ref.message.slice(0,100)+'…':ref.message;m.chainExtract=`${ref.sender}:\n${shortMsg}`}}});return parsed}
function showTopics(){const topicSet=new Set();allMessages.forEach(m=>m.topics.forEach(t=>topicSet.add(t)));uniqueTopics=Array.from(topicSet).sort((a,b)=>{const aNum=parseInt(a.match(/\d+/)?.[0])||0;const bNum=parseInt(b.match(/\d+/)?.[0])||0;return aNum-bNum});topicList.innerHTML=uniqueTopics.map(t=>`<div class="topic-item" onclick="showMessages('${t}')">${t}</div>`).join('')}
function showSenders(){const uniqueSenders=[...new Set(allMessages.map(m=>m.sender))].sort();senderList.innerHTML=`<h3>Senders</h3>`+uniqueSenders.map(s=>`<div class="topic-item" onclick="showSenderMessages('${s.replace(/'/g, "\\'")}')">${s}</div>`).join('')}
function showMessages(topic){headingArea.innerHTML=`పద్యసౌందర్యం <small>${topic}</small>`;chatWrapper.style.display='none';chatOutput.style.display='block';navButtons.style.display='block';tabsArea.style.display='none';chatOutput.innerHTML='';let filtered=(topic==="0. అన్ని సందేశాలు")?allMessages:allMessages.filter(m=>m.topics.includes(topic));filtered.forEach(({sender,message,date,time,subtopic,chainExtract,serial,chainTo})=>{const div=document.createElement('div');const stopic=subtopic.split(",").filter(a=>a.trim()!=topic)
const stlisting=stopic.length>0?`also in ${stopic}`:""
div.className='message';if(typeof serial!=='undefined'){div.id=`msg-${serial}`}
const chained=chainExtract&&chainTo?`<div class="chained"><em><a href="#msg-${chainTo}" onclick="scrollToMessage('${chainTo}'); return false;">↪ ${chainExtract}</a></em></div>`:'';div.innerHTML=`<div class="sender">${sender}</div>${chained}${message}<small>${date} ${time}${topic === "0. అన్ని సందేశాలు" ? ` in ${subtopic}` :  ` ${stlisting}` } </small>`;chatOutput.appendChild(div)});chatOutput.scrollTop=0}
function showSenderMessages(sender){headingArea.innerHTML=`పద్యసౌందర్యం <small>Messages by ${sender}</small>`;chatWrapper.style.display='none';chatOutput.style.display='block';navButtons.style.display='block';tabsArea.style.display='none';chatOutput.innerHTML='';const filtered=allMessages.filter(m=>m.sender===sender);filtered.forEach(({sender,message,date,time,subtopic})=>{const div=document.createElement('div');div.className='message';div.innerHTML=`<div class="sender">${sender}</div>${message}<small>${date} ${time} in ${subtopic}</small>`;chatOutput.appendChild(div)});chatOutput.scrollTop=0}
function toggleTopicView(){headingArea.innerHTML='పద్యసౌందర్యం';chatWrapper.style.display='block';chatOutput.style.display='none';navButtons.style.display='none';tabsArea.style.display='flex';chatOutput.innerHTML='';goUpBtn.style.display='none';goDownBtn.style.display='none'}
function scrollToTop(){chatOutput.scrollTop=0}
function scrollToMessage(serial){const el=document.getElementById(`msg-${serial}`);if(el){el.scrollIntoView({behavior:'smooth',block:'start'});el.classList.add('highlightChained');setTimeout(()=>el.classList.remove('highlightChained'),2000)}else{alert("Referenced message is not visible in this view.")}}
function scrollToBottom(){chatOutput.scrollTop=chatOutput.scrollHeight}
chatOutput.addEventListener('scroll',()=>{const threshold=50;goUpBtn.style.display=chatOutput.scrollTop>threshold?'block':'none';goDownBtn.style.display=(chatOutput.scrollTop+chatOutput.clientHeight<chatOutput.scrollHeight-threshold)?'block':'none'});function printTopic(){window.print()}
function switchTab(tab){const topicBtn=document.querySelector('.tab-button:nth-child(1)');const senderBtn=document.querySelector('.tab-button:nth-child(2)');const topicListDiv=document.getElementById('topicList');const senderListDiv=document.getElementById('senderList');if(tab==='topics'){topicListDiv.style.display='block';senderListDiv.style.display='none';topicBtn.classList.add('active');senderBtn.classList.remove('active')}else{topicListDiv.style.display='none';senderListDiv.style.display='block';senderBtn.classList.add('active');topicBtn.classList.remove('active')}}
let currentIndex=-1;let matches=[];function clearOnClick(input){input.value='';resetHighlights()}
function resetHighlights(){const messages=document.querySelectorAll('.chat-container .message');messages.forEach(msg=>{removeHighlights(msg)});matches=[];currentIndex=-1;document.getElementById('matchCounter').textContent=''}
function removeHighlights(element){const highlights=element.querySelectorAll('mark.highlight');highlights.forEach(mark=>{const textNode=document.createTextNode(mark.textContent);mark.replaceWith(textNode)})}
function searchText(){resetHighlights();const searchTerm=document.getElementById('searchInput').value.trim();if(!searchTerm)return;const messages=document.querySelectorAll('.chat-container .message');const regex=new RegExp(escapeRegExp(searchTerm),'gi');matches=[];messages.forEach(msg=>{highlightInElement(msg,regex)});if(matches.length>0){currentIndex=0;scrollToMatch(currentIndex);updateCounter()}}
function scrollToMatch(index){matches.forEach((m,i)=>m.style.background=i===index?'yellow':'lightgreen');matches[index]?.scrollIntoView({behavior:'smooth',block:'center'})}
function highlightNext(){if(matches.length===0)return;currentIndex=(currentIndex+1)%matches.length;scrollToMatch(currentIndex);updateCounter()}
function highlightPrev(){if(matches.length===0)return;currentIndex=(currentIndex-1+matches.length)%matches.length;scrollToMatch(currentIndex);updateCounter()}
function updateCounter(){document.getElementById('matchCounter').textContent=`${currentIndex + 1} / ${matches.length}`}
function closeSearchBar(){document.getElementById('searchBar').style.display='none';resetHighlights()}
function escapeRegExp(string){return string.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function highlightInElement(element,regex){const walker=document.createTreeWalker(element,NodeFilter.SHOW_TEXT,null,!1);const textNodes=[];while(walker.nextNode()){textNodes.push(walker.currentNode)}
textNodes.forEach(node=>{const parent=node.parentNode;const frag=document.createDocumentFragment();let lastIndex=0;const text=node.textContent;regex.lastIndex=0;let match;while((match=regex.exec(text))!==null){const before=text.slice(lastIndex,match.index);if(before)frag.appendChild(document.createTextNode(before));const mark=document.createElement('mark');mark.className='highlight';mark.textContent=match[0];frag.appendChild(mark);matches.push(mark);lastIndex=regex.lastIndex}
const after=text.slice(lastIndex);if(after)frag.appendChild(document.createTextNode(after));if(frag.childNodes.length){parent.replaceChild(frag,node)}})}